
name: PDF Compile Action
on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    permissions:
      # Required to create a release
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: set git variables
        run: |
            cd ./overleafExample
            git config --global user.name "GitHub Actions Bot"
            git config --global user.email "github-actions-bot@users.noreply.github.com"
            cd ..
      - name: cleanup old pdfs
        run: |
          git rm --ignore-unmatch *.pdf
          git commit --allow-empty -m 'removing old pdfs, github action'
          git push
      - name: Run latexmk
        run: |
          cd ./overleafExample
          latexmk --pdflatex main.tex
      - name: Store build timestamp
        run: echo "BUILD_TIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      - name: change file name
        run: |
          mv ./overleafExample/main.pdf main$BUILD_TIME.pdf
      - name: adding new pdfs
        run: |
          git add main$BUILD_TIME.pdf
          git commit -m 'adding new pdfs, github action'
          git push
